import type { ClinicPatient, ClinicPatientWrite, PatientContact } from './clinic-patients';

export const PATIENTS_ENDPOINT = '/api/clinicconnect/patients';
export class ClinicPatientsClientError extends Error { constructor(message: string, readonly status: number) { super(message); this.name = 'ClinicPatientsClientError'; } }
function message(status: number) { if (status === 400) return 'Check the highlighted patient fields.'; if (status === 401) return 'Your session has expired. Sign in again.'; if (status === 403) return 'Only clinic administrators can manage patients.'; if (status === 404) return 'That patient or contact could not be found in this clinic.'; if (status === 409) return 'That contact is already a patient or already exists.'; return 'Patients are temporarily unavailable. Please try again.'; }
type FetchLike = typeof fetch;
async function parse(response: Response): Promise<unknown> { return response.json().catch(() => null); }
export async function fetchPatients(fetcher: FetchLike = fetch): Promise<ClinicPatient[]> { const response = await fetcher(PATIENTS_ENDPOINT, { cache: 'no-store' }); const body = await parse(response); if (!response.ok) throw new ClinicPatientsClientError(message(response.status), response.status); return (body && typeof body === 'object' && 'patients' in body ? body.patients : []) as ClinicPatient[]; }
export async function fetchPatient(id: string, fetcher: FetchLike = fetch): Promise<ClinicPatient> { const response = await fetcher(`${PATIENTS_ENDPOINT}/${encodeURIComponent(id)}`, { cache: 'no-store' }); const body = await parse(response); if (!response.ok) throw new ClinicPatientsClientError(message(response.status), response.status); const patient = body && typeof body === 'object' && 'patient' in body ? body.patient : null; if (!patient) throw new ClinicPatientsClientError('Patient returned an unexpected response.', 500); return patient as ClinicPatient; }
export async function searchPatientContacts(query: string, fetcher: FetchLike = fetch): Promise<PatientContact[]> { const response = await fetcher(`${PATIENTS_ENDPOINT}?contacts_query=${encodeURIComponent(query)}`, { cache: 'no-store' }); const body = await parse(response); if (!response.ok) throw new ClinicPatientsClientError(message(response.status), response.status); return (body && typeof body === 'object' && 'contacts' in body ? body.contacts : []) as PatientContact[]; }
export async function savePatientRequest(input: ClinicPatientWrite, id?: string, fetcher: FetchLike = fetch): Promise<ClinicPatient> { const response = await fetcher(id ? `${PATIENTS_ENDPOINT}/${encodeURIComponent(id)}` : PATIENTS_ENDPOINT, { method: id ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const body = await parse(response); if (!response.ok) throw new ClinicPatientsClientError(message(response.status), response.status); const patient = body && typeof body === 'object' && 'patient' in body ? body.patient : null; if (!patient) throw new ClinicPatientsClientError('Patient returned an unexpected response.', 500); return patient as ClinicPatient; }
