import type { AppointmentAvailability, ClinicAppointment, ClinicAppointmentWrite } from './clinic-appointments';

export const APPOINTMENTS_ENDPOINT = '/api/clinicconnect/appointments';
export class ClinicAppointmentsClientError extends Error { constructor(message: string, readonly status: number, readonly code?: string) { super(message); this.name = 'ClinicAppointmentsClientError'; } }
function message(status: number, code?: string) { if (code === 'appointment_conflict' || code === 'appointment_unavailable') return 'That appointment time is no longer available.'; if (status === 400) return 'Check the highlighted appointment fields.'; if (status === 401) return 'Your session has expired. Sign in again.'; if (status === 403) return 'Only clinic administrators can manage appointments.'; if (status === 404) return 'The selected appointment resource was not found in this clinic.'; if (status === 409) return 'The appointment could not be booked at that time.'; return 'Appointments are temporarily unavailable. Please try again.'; }
type FetchLike = typeof fetch;
async function parse(response: Response): Promise<{ body: unknown; code?: string }> { const body = await response.json().catch(() => null); return { body, code: body && typeof body === 'object' && 'code' in body && typeof body.code === 'string' ? body.code : undefined }; }
export async function fetchAppointments(filters: { date?: string; doctor_id?: string; patient_profile_id?: string; status?: string } = {}, fetcher: FetchLike = fetch): Promise<ClinicAppointment[]> { const query = new URLSearchParams(filters as Record<string, string>).toString(); const response = await fetcher(`${APPOINTMENTS_ENDPOINT}${query ? `?${query}` : ''}`, { cache: 'no-store' }); const parsed = await parse(response); if (!response.ok) throw new ClinicAppointmentsClientError(message(response.status, parsed.code), response.status, parsed.code); const body = parsed.body; return (body && typeof body === 'object' && 'appointments' in body ? body.appointments : []) as ClinicAppointment[]; }
export async function fetchAppointment(id: string, fetcher: FetchLike = fetch): Promise<ClinicAppointment> { const response = await fetcher(`${APPOINTMENTS_ENDPOINT}/${encodeURIComponent(id)}`, { cache: 'no-store' }); const parsed = await parse(response); if (!response.ok) throw new ClinicAppointmentsClientError(message(response.status, parsed.code), response.status, parsed.code); const body = parsed.body; const appointment = body && typeof body === 'object' && 'appointment' in body ? body.appointment : null; if (!appointment) throw new ClinicAppointmentsClientError('Appointment returned an unexpected response.', 500); return appointment as ClinicAppointment; }
export async function fetchAvailability(input: { doctor_id: string; service_id: string; date: string }, fetcher: FetchLike = fetch): Promise<AppointmentAvailability> { const response = await fetcher(`${APPOINTMENTS_ENDPOINT}/availability?${new URLSearchParams(input)}`, { cache: 'no-store' }); const parsed = await parse(response); if (!response.ok) throw new ClinicAppointmentsClientError(message(response.status, parsed.code), response.status, parsed.code); const body = parsed.body; const availability = body && typeof body === 'object' && 'availability' in body ? body.availability : null; if (!availability) throw new ClinicAppointmentsClientError('Availability returned an unexpected response.', 500); return availability as AppointmentAvailability; }
export async function saveAppointmentRequest(input: ClinicAppointmentWrite, id?: string, fetcher: FetchLike = fetch): Promise<ClinicAppointment> { const response = await fetcher(id ? `${APPOINTMENTS_ENDPOINT}/${encodeURIComponent(id)}` : APPOINTMENTS_ENDPOINT, { method: id ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const parsed = await parse(response); if (!response.ok) throw new ClinicAppointmentsClientError(message(response.status, parsed.code), response.status, parsed.code); const body = parsed.body; const appointment = body && typeof body === 'object' && 'appointment' in body ? body.appointment : null; if (!appointment) throw new ClinicAppointmentsClientError('Appointment returned an unexpected response.', 500); return appointment as ClinicAppointment; }
